spring:
  application:
    name: reports

  config:
    import: configserver:${CONFIG_MANAGER_URL:http://localhost:8000}

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3310}/${MYSQL_SCHEMA:reports}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health

currency-rates:
  provider: COINS
  url: coins.com